SELECT TBVENDEDOR.cdvdd,
       TBVENDEDOR.nmvdd
FROM TBVENDEDOR
JOIN TBVENDAS ON TBVENDEDOR.cdvdd = TBVENDAS.cdvdd
WHERE TBVENDAS.status = 'Concluído'
GROUP BY TBVENDEDOR.cdvdd,
         TBVENDEDOR.nmvdd
ORDER BY COUNT(TBVENDAS.cdven) DESC
LIMIT 1;